### PR TITLE
Current image blank fix

### PR DESCRIPTION
**Pull request by malec**
* update urls

* lint

* lint .github

* formatting, add 'security-captcha' url back

* version bump

* ignore screenshots

* fix current image being blank sometimes

* enable jest debugger

### CODE REVIEW

**Review by arc298 — APPROVED** [review]

**Comment by malec** [comment]
Looks like CI failed, I need to fix the test script

**Comment by arc298** [comment]
Yeah, the tests were not even running. I removed `-maxWorkers=2 ` from the github actions file. However I think it's still failing on windows. I'll take a look later when I get the chance.

**Comment by malec** [comment]
Hmm. I'll check it out on windows. Currently I'm on linux. Tests pass
inconsistently via headless, consistently via non headless (as of
yesterday).

**Comment by malec** [comment]
I'm planning to add a tdd script with watch to run with one worker so the
debugger can be used. Then revert the test script to 'jest'

**Comment by malec** [comment]
Hmm. I'll check it out on windows. Currently I'm on linux. Tests pass
inconsistently via headless, consistently via non headless (as of
yesterday).

**Comment by malec** [comment]
I'm planning to add a tdd script with watch to run with one worker so the
debugger can be used. Then revert the test script to 'jest'

**Comment by arc298** [comment]
Seems as if TikTok detecting chromium being controlled by puppeteer and messing up the response with `ERR_INVALID_RESPONSE`. The tests are more consistent when run in `headless: false`. I've left your changes in.

**Comment by malec** [comment]
This issue can be closed
https://github.com/arc298/tiktok-captcha-solver/issues/6

**Pull request merged**
